### ISSUE TITLE
使用UITextView+WZB 的 placeholder 为什么UITextView会变成第一响应？

### ISSUE THREAD

**Issue by flyweights** [WZBbiao/UITextView-WZB#2]
这样就会和MJRefresh 有冲突了，导致下拉刷新那个view 直接位移了

**Comment by WZBbiao** [comment]
![emo](https://cloud.githubusercontent.com/assets/16611004/21513973/d0e4c2ec-ccf9-11e6-8830-fc14ff235c4c.gif)
未发现您说的下拉刷新视图位移的问题，请您看下是否是别的问题导致的
