### ISSUE TITLE
如何获取textView中的当前高度

### ISSUE THREAD

**Issue by LixinQian** [WZBbiao/UITextView-WZB#4]

**Comment by WZBbiao** [comment]
感谢您提出的问题，一般情况直接拿textView.frame.size.height就行了，在高度随文字改变的时候会调用textViewHeightDidChanged这个block，你可以实现这个block，它会返回给你一个CGFloat currentTextViewHeight，当前高度。具体可以查看demo中ViewController.m中-test2的例子。
